name: TheGameFirm
favicon: null
layout_spectrum: 0.23681
typography_spectrum: 0.06936863670125604
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7626483815256506
  lightness: 0.6354934382252395
  saturation: 0.3896283416543156
  rhythmicContrast: 0.6654384015128016
purpose: []
