typography_spectrum: 0.607991725904867
color:
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  brandStrength: 0.2530884058214724
  lightness: 0.24069221876561642
  saturation: 0.7488903470803052
  rhythmicContrast: 0.48274967982433736
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.9355884999968112
analytics:
  google: null
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/ba66df36-5963-468e-a1ea-7eb12898fb35.png
name: The Game Firm
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: INTERACTIVE IDEATION AND DESIGN
    id: 596edbd9-8f4f-42e5-aced-9a796991d437
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/4ea416af-a8e8-4881-b64c-245af46f479e.png
title: 'The Game Firm • Houston, TX '
description: Interactive Design and Ideation
purpose: []
