name: The Game Firm
favicon: null
layout_spectrum: 0.25233
typography_spectrum: 0.10493
title: 'The Game Firm • Houston, TX '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020202'
    - '#ffffff'
    - '#6d6d6d'
    - '#bfbfbf'
    - '#414141'
  brandStrength: 0
  lightness: 0.6875
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
