layout_spectrum: 0.9355884999968112
typography_spectrum: 0.607991725904867
color:
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  brandStrength: 0.2530884058214724
  lightness: 0.24069221876561642
  saturation: 0.7488903470803052
  rhythmicContrast: 0.48274967982433736
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: The Game Firm
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: 'The Game Firm • Houston, TX '
description: Interactive Design and Ideation
purpose: []
